### ISSUE TITLE
Event reader and writer seem to be flipped

### ISSUE THREAD

**Issue by guyguy2001** [devlike-code/bevyrly#6]
The docs say that a left arrow indicates an event reader, and a right one indicates an event writer:
```
<ShipFireEvent: find all systems that include EventReader<ShipFireEvent> within it
>ShipFireEvent: find all systems that include EventWriter<ShipFireEvent> within it
```
![image](https://github.com/devlike-code/bevyrly/assets/6932278/dd0d8cf5-17b1-4070-805d-89a7d75c7bdf)

But when I use this in my editor, I get the opposite behaviour:
![image](https://github.com/devlike-code/bevyrly/assets/6932278/887cc252-84ca-44af-a51a-bf16dd7a089f)

I might solve this issue next weekend if you don't get to it - but which of these is the intended behavior? Or am I completely missing something here?

**Comment by gavrilovmiroslav** [comment]
Oh you're right with this! I'm not sure which one makes sense, which I think led to this error in the first place: my initial idea was to have the `<` mark incoming (so writing), and `>` mean outgoing (so reading), but maybe I should just find other symbols for this? What makes more sense to you? I can finish it this weekend, as soon as we agree on some notation that would be clearer!

**Comment by guyguy2001** [comment]
Hmm, good question
I think that when I read the docs, it made perfect sense to me that `>ShipFireEvent` means that something is going into the ShipFireEvent - meaning that a system is writing _into_ the event queue, while in `<ShipFireEvent`, it's going from the event to the system.

I'll ask some friends about this and see what comes up

**Comment by gavrilovmiroslav** [comment]
This _does_ make sense. An option I've seen used in message-passing would be to have `?Event` for reading and `!Event` for writing, so that we lose the directionality

**Comment by guyguy2001** [comment]
I asked two friends about this, and each one said a different option, but both agreed that they feel like it's relatively arbitrary; I think the bevy discord would be a better place to ask though (I won't have time to try myself in the next days though)

Your idea also sounds great, my only concern is that ? and ! could be very useful for other stuff, and I feel like binding them to the events might be a waste; But if > and < are confusing, then I'm sure that events would be the best use for ? and !.

**Comment by gavrilovmiroslav** [comment]
I'd want to escape the arbitrariness, so let's go with `?` and `!` for reader and writer, respectively. I'll make the change tomorrow :)

**Comment by gavrilovmiroslav** [comment]
@guyguy2001 there was actually an error in the code - a switch case was targeting the wrong read/write pair, but I changed it to `?` and `!` everywhere. Thank you for this!
